services:
  zoo-postgres:
    image: postgres:16.3
    container_name: zoo-postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: "zoo"
      POSTGRES_USER: "zoo"
      POSTGRES_PASSWORD: "zoo"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
       - zoo-backend
    ports:
      - "5400:5432"

  zoo-api:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: zoo
    container_name: zoo
    networks:
      - zoo-backend
    depends_on:
      - zoo-postgres
    ports:
      - "8800:8080"

networks:
  zoo-backend:
