server:
  port: 8080

spring:
  application:
    name: zoo-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
#    url: jdbc:postgresql://db:5432/zoo   // TODO: Перед деплойем поменять на вот это, а нижнее закоментить или убрать
    url: jdbc:postgresql://localhost:5400/zoo
    username: zoo
    password: zoo
    driver-class-name: org.postgresql.Driver

logging:
  config: 'classpath:log4j2.yml'