server:
  port: 8100

spring:
  application:
    name: zoo-api
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://backend:5400/zoo
    username: zoo
    password: zoo
    driver-class-name: org.postgresql.Driver
