server:
  port: 8080

spring:
  application:
    name: zoo-api
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://db:5432/zoo
    username: zoo
    password: zoo
    driver-class-name: org.postgresql.Driver
